// Code generated by "enumer -text -type MessageType,State --output service_enumer.go service.go"; DO NOT EDIT.

//
package main

import (
	"fmt"
)

const _MessageTypeName = "MessageStateMessageString"

var _MessageTypeIndex = [...]uint8{0, 12, 25}

func (i MessageType) String() string {
	if i < 0 || i >= MessageType(len(_MessageTypeIndex)-1) {
		return fmt.Sprintf("MessageType(%d)", i)
	}
	return _MessageTypeName[_MessageTypeIndex[i]:_MessageTypeIndex[i+1]]
}

var _MessageTypeValues = []MessageType{0, 1}

var _MessageTypeNameToValueMap = map[string]MessageType{
	_MessageTypeName[0:12]:  0,
	_MessageTypeName[12:25]: 1,
}

// MessageTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func MessageTypeString(s string) (MessageType, error) {
	if val, ok := _MessageTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to MessageType values", s)
}

// MessageTypeValues returns all values of the enum
func MessageTypeValues() []MessageType {
	return _MessageTypeValues
}

// IsAMessageType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i MessageType) IsAMessageType() bool {
	for _, v := range _MessageTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for MessageType
func (i MessageType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for MessageType
func (i *MessageType) UnmarshalText(text []byte) error {
	var err error
	*i, err = MessageTypeString(string(text))
	return err
}

const _StateName = "StateDeadStateStartedStateRunningStateFinishedStateFailed"

var _StateIndex = [...]uint8{0, 9, 21, 33, 46, 57}

func (i State) String() string {
	if i < 0 || i >= State(len(_StateIndex)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _StateName[_StateIndex[i]:_StateIndex[i+1]]
}

var _StateValues = []State{0, 1, 2, 3, 4}

var _StateNameToValueMap = map[string]State{
	_StateName[0:9]:   0,
	_StateName[9:21]:  1,
	_StateName[21:33]: 2,
	_StateName[33:46]: 3,
	_StateName[46:57]: 4,
}

// StateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StateString(s string) (State, error) {
	if val, ok := _StateNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to State values", s)
}

// StateValues returns all values of the enum
func StateValues() []State {
	return _StateValues
}

// IsAState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i State) IsAState() bool {
	for _, v := range _StateValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for State
func (i State) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for State
func (i *State) UnmarshalText(text []byte) error {
	var err error
	*i, err = StateString(string(text))
	return err
}
